version: '3.9'

services:
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    # image: neo4j:latest-enterprise
    # environment:
    #   - NEO4J_AUTH=neo4j/neo4j/neo4j12
    #   - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - 7474:7474
      - 7687:7687
      - 7473:7473
    networks:
      - net

networks:
  net:

# http://localhost:7474/
# default user/password neo4j/neo4j